### ISSUE TITLE
Increase golangci-lint  timeout

### ISSUE THREAD

**Issue by hzxuzhonghu** [kurator-dev/kurator#11]
I have met https://github.com/kurator-dev/kurator/runs/6959249310?check_suite_focus=true

```
level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
make: *** [golangci-lint] Error 1
```

cc @gy95

**Comment by gy95** [comment]
maybe has been fixed in https://github.com/kurator-dev/kurator/pull/8, I have change the default timeout from 1m to 5m

**Comment by gy95** [comment]
ref: https://github.com/kurator-dev/kurator/blob/97d3f7cbb0cd888ba04c9665e369dbc7cf62698a/.golangci.yml#L4-L6

**Comment by hzxuzhonghu** [comment]
OK
