### ISSUE TITLE
Change docker image hub to `docker.io/kuratordev`

### ISSUE THREAD

**Issue by hzxuzhonghu** [kurator-dev/kurator#122]
Have created an account in dockerhub,  since `kurator` was used by other org. We named `kuratordev`, which aligns with kurator domain.

#### Why do not register `kurator-dev`?

Because docker hub only supports letters and digitals

**Comment by zirain** [comment]
https://github.com/kurator-dev/kurator/pull/125 will push latest image to `ghcr.io`.

**Comment by zirain** [comment]
fixed by https://github.com/kurator-dev/kurator/pull/125

**Comment by hzxuzhonghu** [comment]
Yep, we choose ghcr as our image registry atm
