### ISSUE TITLE
Enhancement of CustomCluster

### ISSUE THREAD

**Issue by zirain** [kurator-dev/kurator#128]
- [ ] [support custom registry of kubespray](https://github.com/kurator-dev/kurator/pull/114#discussion_r1072113678)
- [ ] [support other kubernetes configs](https://github.com/kurator-dev/kurator/pull/114#discussion_r1073044167)
- [ ] support accessing k8s api from outside of the provisioned cluster 
- [ ] #152

cc @hzxuzhonghu @Xieql

**Comment by hzxuzhonghu** [comment]
assign @Xieql

**Comment by hzxuzhonghu** [comment]
ping @Xieql
