### ISSUE TITLE
can you provide more details on how to apply aws credentials  in aws cluster operator

### ISSUE THREAD

**Issue by worstkid92** [kurator-dev/kurator#130]
**What would you like to be added**:
actions on how to apply aws credentials  in aws cluster operator

**Why is this needed**:
stuck on creating aws machine due to lack of credentials

**Comment by hzxuzhonghu** [comment]
We should supplement docs about it

**Comment by zirain** [comment]
fixed by https://github.com/kurator-dev/kurator/pull/132
