### ISSUE TITLE
kurator looks like a one-stop platform

### ISSUE THREAD

**Issue by prodanlabs** [kurator-dev/kurator#16]
**Please provide an in-depth description of the question you have**:

Does kurator just install cloud-native application services?  Is there anything else planned.

I am interested in kurator.

**What do you think about this question?**:

**Environment**:
- Kurator version:
- Others:

**Comment by prodanlabs** [comment]
Are there plans for a cloud-native software integration solution? For example, the combination of thanos and prometheus

**Comment by hzxuzhonghu** [comment]
Currently, we have a very coarse  roadmap https://github.com/kurator-dev/kurator/blob/main/ROADMAP.md

I think this can be updated accordingly.  About multicluster monitor we have supported Prometheus federation now. thanos can be another choice

**Comment by prodanlabs** [comment]
Thank you for your reply.

/close
