### ISSUE TITLE
Updating api group

### ISSUE THREAD

**Issue by hzxuzhonghu** [kurator-dev/kurator#162]
**What would you like to be added**:

**Why is this needed**:

Currently, we have `"infra.kurator.dev"` and `"cluster.kurator.dev"` API groups, however infra group is on the top of `cluster.kurator.dev`. Cluster operator will translate the cluster's spec to the underlying cluster in `cluster.kurator.dev` group.

This makes me feel the hierarchy of clusters is reversed. 

The proposed hierarchy should be `cluster.kurator.dev`  -> `infra.kurator.dev`, and eventually `infra.kurator.dev` should be gone, and we directly use `cluster.kurator.dev`

**Comment by zirain** [comment]
following Cluster API's practice, `CustomCluster` should in `infrastructure.cluster.x-k8s.io` group

xref: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/cdbaf654af78585d507ba333c10ce3e678944616/api/v1beta2/groupversion_info.go#L29

**Comment by hzxuzhonghu** [comment]
Yes, we met some issuse and we added labels for CRD.
