### ISSUE TITLE
make gen-check failed

### ISSUE THREAD

**Issue by gy95** [kurator-dev/kurator#19]
**What happened**:
make gen-check failed
```
# make gen-check 
go mod tidy -compat=1.17
go clean -testcache
go clean -cache
rm -rf out/linux-amd64
rm -rf out/prom
go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
go install -a github.com/brancz/gojsontoyaml@latest
go install -a github.com/google/go-jsonnet/cmd/jsonnet@latest
rm -rf manifests/profiles/prom/
mkdir -p manifests/profiles/prom/
mkdir -p out/prom
cp manifests/jsonnet/kube-prometheus.jsonnet out/prom
hack/gen-prom.sh out/prom v0.10.0 kube-prometheus.jsonnet
begin to generate prom manifests
path: out/prom
version: v0.10.0
jsonnet file: kube-prometheus.jsonnet
~/go/src/github.com/kurator-dev/kurator/out/prom ~/go/src/github.com/kurator-dev/kurator
hack/gen-prom.sh: line 13: jb: command not found
Makefile:65: recipe for target 'gen-prom' failed
make: *** [gen-prom] Error 127
```
Solutions:
we should `export PATH=$PATH:$GOPATH/bin` after we install jb
https://github.com/kurator-dev/kurator/blob/33fef92a4a7386d6706a4de1366f5bbf96c2215d/Makefile#L57-L61

or we can use the function defined in util.sh
https://github.com/kurator-dev/kurator/blob/33fef92a4a7386d6706a4de1366f5bbf96c2215d/hack/util.sh#L13-L20
but i don't know how to run functions of shell script in Makefile

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kurator version:
- Others:

**Comment by hzxuzhonghu** [comment]
good catch @gy95 

we donot need to expose install-tools, which is now used by gen-prom

I am thinking we can move the install into hack/gen-prom.sh

**Comment by gy95** [comment]
That's a good way.
