### ISSUE TITLE
[Umbrella] Add `tool` subcommand

### ISSUE THREAD

**Issue by prodanlabs** [kurator-dev/kurator#24]
**Please provide an in-depth description of the question you have**:

According to the `issues` discussion, add the `tool` subcommand to output information such as the version of tools, and download tools.

task:

- [ ]  add `tool list` subcommand , output toos information.
- [ ]  add `tool install` subcommand, download tools.

**Comment by hzxuzhonghu** [comment]
Make sense to me. These binaries can be widely used when adopting an associated software stack

**Comment by prodanlabs** [comment]
My idea is to use a subcommand to maintain the lifecycle of these binaries.

E.g.
```
kurator plugin download
kurator plugin {get or list} # List binaries and print versions etc.
kurator plugin update
```
hi @hzxuzhonghu , do you have any advice? Looking forward to your reply.

**Comment by hzxuzhonghu** [comment]
Where do you think the binaries should be put

**Comment by hzxuzhonghu** [comment]
I am thinking may be we should call tools instead of plugins, plugin is widely used and is wider than binary cli tool. 

And during installation, we have downloaded the tools into $HOME/.kurator/xxx. So my suggestion is maybe put them under $HOME/.kurator/ 

`kurator tool install/list/update` should work

**Comment by prodanlabs** [comment]
How about putting it in $HOME/.kurator/bin/xxx, and adding $HOME/.kurator/bin to PATH.

**Comment by prodanlabs** [comment]
>And during installation, we have downloaded the tools into $HOME/.kurator/xxx.

The path I see is in `/usr/local/bin`, did you download it to `$HOME/.kurator/` first and then move it to `/usr/local/bin`?
[$HOME/.kurator/](https://github.com/kurator-dev/kurator/blob/main/pkg/plugin/istio/plugin.go#L60)

**Comment by hzxuzhonghu** [comment]
You are right, i kind of forget that

**Comment by prodanlabs** [comment]
I took a quick look at the code, and the binary is downloaded during the install process, but not if it already exists, so I think `kurator tool update` makes more sense than `kurator tool install`.

Or check the binary version during the installation process, and update it if it is inconsistent.

https://github.com/kurator-dev/kurator/blob/main/pkg/plugin/istio/plugin.go#L108-L111

**Comment by hzxuzhonghu** [comment]
Tool and plugin are separate, though pulgin installation may rely on tool sometimes. A separate command to only install cli tool is necessary, think about the case, user may need just a `kubectl` installed for them. 

>kurator tool update makes more sense than kurator tool install.

FYI kurator support the latest stable version listed `manifests/profiles/components.yaml`, i think we can do install as the first step

**Comment by prodanlabs** [comment]
> FYI kurator support the latest stable version listed manifests/profiles/components.yaml, i think we can do install as the first step

agree.

But what I mean is that if the binary already exists and the version is inconsistent with `manifests/profiles/components.yaml`, then it needs to be updated.

**Comment by prodanlabs** [comment]
Maybe it's too early to discuss this.

**Comment by prodanlabs** [comment]
```bash
# ./kurator tool list
NAME              CURRENT-VERSION   DESIRED-VERSION     PATH
istioctl          1.14.1            1.14.1              /usr/local/bin/istioctl
keadm             1.10.0            1.10.0              /usr/local/bin/keadm
kubectl-karmada   v1.2.0            v1.1.1              /usr/local/bin/kubectl-karmada
```
`DESIRED-VERSION`  is the version declared by the `manifests/profiles/components.yaml`

**Comment by prodanlabs** [comment]
My fault, there is no need to change anything.

/close

**Comment by hzxuzhonghu** [comment]
>My fault, there is no need to change anything.

Confused, we have not achived all what we talked above

**Comment by zirain** [comment]
> The installation process of kurator is to go to `/usr/local/bin` to find out if there are any tools, if it does not exist, download and save it to `$HOME/.kurator/xxx/version` according to the version declared in `manifests/profiles/components.yaml`
> 
> Now the question, tools under `/usr/local/bin`, does kurator need to manage its life cycle
> 
> case 1 : No remove this code https://github.com/kurator-dev/kurator/blob/main/pkg/plugin/istio/plugin.go#L60
> 
> case 2: Yes
> 
> 1. Because install uses the tools under `/usr/local/bin` first, when the tools of `/usr/local/bin` exist, kurator needs to determine whether its version is the same as that declared in `manifests/profiles/components.yaml` the same version.
> 2. Add `kurator tool install/list/update` subcommand.
> 
> I don't know if I'm right，my idea is `case 2` /cc @hzxuzhonghu
> 
> /open

the original thought is `do not override /usr/local/bin`
I'm ok with adding new cmd named `kurator tool`, but perfer to `kurator tool install [plugin]`.
IMO, it's not a good way to install/upgrade all binary in the same time, it may cost too much time.

**Comment by zirain** [comment]
@prodanlabs do you still working on this?

**Comment by zirain** [comment]
yes, `/usr/local/bin` will be used as fallback.
IMO, this's still needed, especially in an unstable network, we can download binary first.

**Comment by zirain** [comment]
a little more think
we should support in `kurator tool install all/istio/[other plugin]`, but I do not have strong option of make `all`  as default.

**Comment by prodanlabs** [comment]
I think we just need to maintain the version below `.kurator`. For example, there may be an inconsistency between the component version of `/usr/local/bin` and the version declared in `components.yaml`.

**Comment by zirain** [comment]
> I think it's fine to just maintain the components in the `.kurator` directory. For example, there may be an inconsistency between the component version of `/usr/local/bin` and the version declared in `components.yaml`.

yes, that's the original thought

**Comment by prodanlabs** [comment]
For users with restricted or poor access to the `github` network (such as mainland China), `kurator plugin download` can provide the option to download components through `https://ghproxy.com` proxy, which makes sense to me.

**Comment by hzxuzhonghu** [comment]
@prodanlabs Would you want to take over?

**Comment by prodanlabs** [comment]
Sorry, I'm busy at this time.

I'm still thinking about how to make this function more useful.
