### ISSUE TITLE
Add a "About" description on Kurator github page

### ISSUE THREAD

**Issue by Xieql** [kurator-dev/kurator#263]
**What would you like to be added**:

add a "About" description on Kurator github page

**Why is this needed**:

Since we already have a documentation website for Kurator at https://kurator.dev/docs/, it would be beneficial to include a brief description and a link to the website on the Kurator Github page, similar to how Istio and Kubernetes have done.

![Istio-about](https://user-images.githubusercontent.com/45359033/231920873-8376692f-2550-4526-ab7d-add00c1d7111.PNG)

**Comment by hzxuzhonghu** [comment]
done
