### ISSUE TITLE
Enhance fleet manager

### ISSUE THREAD

**Issue by hzxuzhonghu** [kurator-dev/kurator#317]
When i installed fleet manager according to the doc, i met a couple of failures.

1. failed to wait for application sync. (The doc is missing ?)
2. when i did not even create an application, i met HelmRepo list failure. (This is because i did not install flux)

For 2, WDYT @zirain @Xieql

**Comment by zirain** [comment]
make FluxCD installation as part of setup Fleet Manager?

**Comment by zirain** [comment]
fixed by #310 

/close
