### ISSUE TITLE
kurator install supports specifying component configuration files

### ISSUE THREAD

**Issue by prodanlabs** [kurator-dev/kurator#32]
**Please provide an in-depth description of the question you have**:
The components component configuration file of kurator is embedded in the binary file. If the user needs to modify the components component configuration file, it will be very inconvenient.

**What do you think about this question?**:
Can `kurator install` add a flag to use the local component configuration file.I don't know if this is possible.

**Environment**:
- Kurator version:
- Others:

**Comment by zirain** [comment]
IIRC, this should be supported, maybe I missed, let me figure out.
