### ISSUE TITLE
Are there any plans to support KubeVela

### ISSUE THREAD

**Issue by prodanlabs** [kurator-dev/kurator#37]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Kurator version:
- Others:

**Comment by prodanlabs** [comment]
## 2023 H1
- Integrate more software stacks:
  - CI/CD

As Roadmap said, I don't know if ci/cd supports the KubeVela plan.

**Comment by zirain** [comment]
I'm not that familiar with KubeVela, but how do kurator work with KubeVela in your mind?

**Comment by prodanlabs** [comment]
We are also not currently using KubeVela on karmada. I was thinking, KubeVela can support karmada like `OCM`.

Maybe I'll go to the KubeVela community to find the answer.

**Comment by prodanlabs** [comment]
Temporarily closed, I need to do more research.

/close
