### ISSUE TITLE
[FR] Unified Backup, Restore, and Migration

### ISSUE THREAD

**Issue by Xieql** [kurator-dev/kurator#404]
# Feature Requirements
This page lists the requirements for Unified Backup, Restore, and Migration with Fleet.

**Proposal**: 
 * [x] #374

## Requirements:

* [x] **API**:
- * [x] Fleet Backup Plugin: #378

- * [x] Unified Backup, Restore, and Migration #377, #393 

* [x] **Controller**:
- * [x] Fleet Backup Plugin:  #381 
- * [x] Backup  #394 #406 
- * [x] Restore  #407 
- * [x] Migrate #408

* [ ] **Webhook**:
- * [ ] Backup #410 
- * [ ] Restore #411
- * [ ] Migrate #412 

* [x] **Docs**:
- * [x] What is Unified Backup, Restore, and Migration with Fleet. #405 
- * [x] How to manager Fleet Backup Plugin. #391 
- * [x] How to use Unified Backup with Kurator.  #414
- * [x] How to use Unified Restore with Kurator.  #419 
- * [x] How to use Unified Migrate with Kurator.  #420

**Comment by LiZhenCheng9527** [comment]
Has this requirement been completed? Or is there a remaining unfinished part?

**Comment by Xieql** [comment]
> Has this requirement been completed? Or is there a remaining unfinished part?

no, and we can close this issue.
