### ISSUE TITLE
Can a service `istiod` of type NodePort be supported

### ISSUE THREAD

**Issue by prodanlabs** [kurator-dev/kurator#41]
**Please provide an in-depth description of the question you have**:
I'm not sure if `istiod` necessarily needs a service of type LoadBalancer.
https://github.com/kurator-dev/kurator/blob/main/pkg/plugin/istio/install.go#L315-L347

There is another question, why is `ingress.Hostname` judged here
https://github.com/kurator-dev/kurator/blob/main/pkg/plugin/istio/install.go#L462

I use Cloud LoadBalancer, but the LoadBalancer Ingress Hostname of `istiod-elb` is empty. I'm a little confused.

**What do you think about this question?**:

**Environment**:
- Kurator version:
- Others:

**Comment by zirain** [comment]
> I'm not sure if istiod necessarily needs a service of type LoadBalancer.

this's the easiest way for beginner

> I use Cloud LoadBalancer, but the LoadBalancer Ingress Hostname of istiod-elb is empty. I'm a little confused.

this's a feature confirmed by karmada maintainers.

**Comment by prodanlabs** [comment]
@zirain thank you for your reply.

>this's a feature confirmed by karmada maintainers.

I go to debug.
