### ISSUE TITLE
[FR]Provide a CI/CD Solution for Kurator

### ISSUE THREAD

**Issue by Xieql** [kurator-dev/kurator#435]
**What would you like to be added**:
The Kurator project requires a CI/CD solution that includes CI pipeline and enhanced CD.  @hzxuzhonghu 

* [ ] **CI pipeline** @Xieql 
* [ ] **enhanced CD** @LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
**What would you like to be added**:
Kurator needs a CD process that enables blue-green, grey-scale and Canary. to enable incremental delivery of new code. Avoid costly rollbacks and fixes don't

 * [ ] Give a design for Kurator CD
 * [ ]  Complete API design
 * [ ]  Complete functional development and UT test
 * [ ] Perform functional testing
 * [ ] Improve the use of documentation

**Comment by Xieql** [comment]
the requirements for CI pipeline：
* [ ] **proposal**
* [ ] **pipeline api**
* [ ] **controller**
* [ ] **doc**

**Comment by LiZhenCheng9527** [comment]
I've done my part.
