### ISSUE TITLE
The labels in the PR template are not consistent in the actual labels

### ISSUE THREAD

**Issue by Xieql** [kurator-dev/kurator#440]
**What would you like to be added**:
add `kind/design` label here

![捕获](https://github.com/kurator-dev/kurator/assets/45359033/575888d3-f3c3-4cce-ac81-3ab8aeeafb04)

**Why is this needed**:
The labels in the PR template are not consistent in the actual labels

![捕获](https://github.com/kurator-dev/kurator/assets/45359033/69b2a613-cf21-44bc-8713-01e07a148fac)

![捕获](https://github.com/kurator-dev/kurator/assets/45359033/b09a696a-7098-4510-b3fa-e85127e5c2e7)

**Comment by hzxuzhonghu** [comment]
It is fixed now
