### ISSUE TITLE
istio install  eastwest gateway

### ISSUE THREAD

**Issue by prodanlabs** [kurator-dev/kurator#45]
**Please provide an in-depth description of the question you have**:
First the `eastwest` gateway makes sense to me. 
I executed `kurator install istio --primary dev-cluster-01 --remote dev-cluster-02`, and `eastwest` gateway was not installed.

**What do you think about this question?**:

I just want, is it possible to install `eastwest` gateway by default.

**Environment**:
- Kurator version:
- Others:

**Comment by prodanlabs** [comment]
```bash
kubectl get po,svc -n istio-system 
NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-ingressgateway-859f7bd7bc-t6qss   1/1     Running   0          2m26s
pod/istiod-5c57f987ff-jzwgn                 1/1     Running   0          2m30s

NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                      AGE
service/istio-ingressgateway   LoadBalancer   10.254.15.197    8.218.38.164     15021:31998/TCP,80:31763/TCP,443:30761/TCP   2m26s
service/istiod                 ClusterIP      10.254.215.75    <none>           15010/TCP,15012/TCP,443/TCP,15014/TCP        2m30s
service/istiod-elb             LoadBalancer   10.254.208.133   47.243.250.150   15012:30463/TCP                              3m12s
```

**Comment by zirain** [comment]
you can try something like [this](https://github.com/zirain/playground/blob/master/istio/multicluster/primary-remote/not-flat/iop/primary-eastwest.yaml)

**Comment by prodanlabs** [comment]
> you can try something like [this](https://github.com/zirain/playground/blob/master/istio/multicluster/primary-remote/not-flat/iop/primary-eastwest.yaml)


Thank you for your reply.

I mean, when install istio, can we choose to install the eastwest gateway through a flag. For example `--eastwest-gateway=true`

**Comment by zirain** [comment]
@prodanlabs we're thinking about support non-flat network, so it would be `--network-mode non-flat/flat`, WDYT?

**Comment by prodanlabs** [comment]
> we're thinking about support non-flat network

Refers to the fact that the network between the cross-cluster Pods cannot be directly connected ?

**Comment by zirain** [comment]
> > we're thinking about support non-flat network
> 
> Refers to the fact that the network between the cross-cluster Pods cannot be directly connected ?

yes, you want use eastwest-gatway on flat network?

**Comment by prodanlabs** [comment]
> you want use eastwest-gatway on flat network?

We don't currently have this scene.

**Comment by prodanlabs** [comment]
By the way, does the Istio Install model allow users to choose between `Primary-Remote` or `Multi-Primary`.

**Comment by hzxuzhonghu** [comment]
Currently, we do not support this option
