### ISSUE TITLE
report a vulnerability link is unreachable

### ISSUE THREAD

**Issue by Xieql** [kurator-dev/kurator#460]
**What happened**:
the "report a vulnerability " link is unreachable in https://github.com/kurator-dev/kurator

![image](https://github.com/kurator-dev/kurator/assets/45359033/214425de-f98a-4e72-8656-deba00aa6898)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kurator version:
- Others:

**Comment by Xieql** [comment]
@LiZhenCheng9527

**Comment by LiZhenCheng9527** [comment]
It is [fixed](https://github.com/kurator-dev/kurator/pull/461) broken link in README.md.
