### ISSUE TITLE
support more complex network mode in istio

### ISSUE THREAD

**Issue by zirain** [kurator-dev/kurator#47]
In https://github.com/kurator-dev/kurator/pull/46 we add non-flat mode about istio, but in a real world the typology of clusters may more complex.
thinking about a network typology like following:

![istio-network-topology](https://user-images.githubusercontent.com/4354057/181867343-7a645595-bebf-45c9-973f-f958775b9ed3.svg)

we need a mechanism to support this but can be used in other plugin.

cc @hzxuzhonghu @prodanlabs

**Comment by prodanlabs** [comment]
It makes sense to me. As you said, there are actually more complex hybrid cloud network environments for application scenarios.

Maybe consider `admiral`, but I don't know much about it.

**Comment by zirain** [comment]
plan to add annotation like `topology.istio.io/network: network2` on `Cluster` CRD in karmada
