### ISSUE TITLE
add an issue template for applying for joining security membership. 

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kurator-dev/kurator#496]
**What would you like to be added**:
An issue template for Company or organisation applying to join private distributors list.
**Why is this needed**:
If a company or organisation uses Kurator. we should give them a way to join the private distribution list for security vulnerabilities. Avoid losses due to Kurator vulnerabilities.

**Comment by Xieql** [comment]
how about "Add an issue template to apply for joining the security membership."
