### ISSUE TITLE
kurator install should be idempotent

### ISSUE THREAD

**Issue by hzxuzhonghu** [kurator-dev/kurator#53]
I have met after install some component with kurator failed the first time, it always fails afterwards.
One cause I have found is that some resources can be created at the first time, but the second time it still create same resources.  That can happen on helm client now.

Not sure if there are other places that is not idempotent, need to investigate.

**Comment by prodanlabs** [comment]
Yes, such as installing `istio`, the first installation has initialized resources such as CRDs. If it fails, you need to delete these resources before re-installation

**Comment by hzxuzhonghu** [comment]
Another point I found is some intermediate output(secret , leader election configmap/endpoint, etc) can be generated, we need to clean them up too.

**Comment by zirain** [comment]
- [ ] istio https://github.com/kurator-dev/kurator/pull/84
- [ ] thanos 
- [ ] argocd
- [ ] karmada
- [ ] kubeedge
- [ ] submariner
- [ ] volcano
- [ ] pixie
- [ ] prometheus

cc @Xieql

**Comment by Xieql** [comment]
> * [x]  istio [istio: make install idempotent #84](https://github.com/kurator-dev/kurator/pull/84)
> * [ ]  thanos 
> * [ ]  argocd
> * [ ]  karmada
> * [ ]  kubeedge
> * [ ]  submariner
> * [x]  volcano #90 
> * [ ]  pixie
> * [x]  prometheus #90
