### ISSUE TITLE
support pixie as part of observability

### ISSUE THREAD

**Issue by zirain** [kurator-dev/kurator#60]
plan to add [pixie](https://docs.pixielabs.ai/) as new observability plugin:

- support install pixie vizier
- support install pixier cloud

cc @hzxuzhonghu @prodanlabs any further idea?

**Comment by hzxuzhonghu** [comment]
This is a great feature

**Comment by prodanlabs** [comment]
I don't know much about it. But it looks interesting.

**Comment by hzxuzhonghu** [comment]
This is the related pr https://github.com/kurator-dev/kurator/pull/62

**Comment by hzxuzhonghu** [comment]
update: This PR has been merged, we still need a doc about it.

**Comment by zirain** [comment]
I will send a PR about how to use pixie later

**Comment by zirain** [comment]
linked to https://github.com/kurator-dev/kurator/pull/70
