### ISSUE TITLE
refactor components.yaml

### ISSUE THREAD

**Issue by zirain** [kurator-dev/kurator#61]
**What would you like to be added**:

split `components.yaml` to two parts:

- `tools.yaml` describe how to get binary like `helm`, `karmadactl` etc
- `components.yaml`(rename to `plugin.yaml`) describe to relationship between `component` and `tool` `chart` and other things

cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
For a component,  we may need CLI, Release package or Manifest
In most cases, CLI can be found in the release package.

**Comment by zirain** [comment]
I think we won't need this anymore, willing to use CRD in the future.
