### ISSUE TITLE
社区有些不活跃了，还在继续维护吗？？

### ISSUE THREAD

**Issue by kinbod** [kurator-dev/kurator#647]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Kurator version:
- Others:

**Comment by hzxuzhonghu** [comment]
Yes, we do maintian it.  We have some undergoing features being discussed.

**Comment by kinbod** [comment]
Ok, it is nice to hear that. It is good news.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: hzxuzhonghu ***@***.***>
发送时间: Monday, July 1, 2024 9:19:01 AM
收件人: kurator-dev/kurator ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [kurator-dev/kurator] 社区有些不活跃了，还在继续维护吗？？ (Issue #647)


Yes, we do maintian it. We have some undergoing features being discussed.

―

**Comment by hzxuzhonghu** [comment]
What features do you mostly concern about? We want some feedbacks

**Comment by kinbod** [comment]
Cluster Management, Cluster backup & restore,  app logs, app monitor

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: hzxuzhonghu ***@***.***>
发送时间: Monday, July 1, 2024 9:26:30 AM
收件人: kurator-dev/kurator ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [kurator-dev/kurator] 社区有些不活跃了，还在继续维护吗？？ (Issue #647)


What features do you mostly concern about? We want some feedbacks

―

**Comment by hzxuzhonghu** [comment]
Good to know that, which indurstry do you use those functionalities
