### ISSUE TITLE
Unable to switch kubeconfig

### ISSUE THREAD

**Issue by Flying-Tom** [kurator-dev/kurator#665]
**What happened**:

The first specified kubeconfig works properly after each restart, but switching others will result in errors.

e.g., after a root, `kubectl get pods --all-namespaces --kubeconfig=/root/.kube/kurator-host.config` was executed and then use `--kubeconfig=/root/.kube/kurator-member1.config` or `--kubeconfig=/root/.kube/kurator-member2.config` will cause the following errors

```
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

**What you expected to happen**:

The kubeconfig can be switched normally.

**How to reproduce it (as minimally and precisely as possible)**:

host, member1 and member2 are created by "hack/local-dev-setup.sh", using `kindest/node:v1.29.4`

**Anything else we need to know?**:

**Environment**:
- Kurator version: 1.0-dev
- Kubernetes version: v1.29.7
- System Info: Ubuntu 22.04 (kvm)

**Comment by LiZhenCheng9527** [comment]
Can you guarantee that `path` are all right?

**Comment by Flying-Tom** [comment]
> Can you guarantee that `path` are all right?

Which is the `path` meaning?

**Comment by LiZhenCheng9527** [comment]
`kurator-member1.config` and `kurator-member2.config`

**Comment by Flying-Tom** [comment]
> `kurator-member1.config` and `kurator-member2.config`

Yes, `/root/.kube/kurator-member1.config`, `/root/.kube/kurator-member2.config` are valid paths and the file exist.

```bash
root@whoami: file /root/.kube/kurator-member1.config
/root/.kube/kurator-member1.config: ASCII text, with very long lines (2261)

**Comment by LiZhenCheng9527** [comment]
> > `kurator-member1.config` and `kurator-member2.config`
> 
> Yes, `/root/.kube/kurator-member1.config`, `/root/.kube/kurator-member2.config` are valid paths and the file exist.
> 
> ```shell
> root@whoami: file /root/.kube/kurator-member1.config
> /root/.kube/kurator-member1.config: ASCII text, with very long lines (2261)
> ```
You can open a new terminal window and try `export KUBECONFIG=/root/.kube/kurator-member.config`

**Comment by Flying-Tom** [comment]
> export KUBECONFIG=/root/.kube/kurator-member.config

I remove the `export KUBECONFIG` in my `.zshrc` and reboot, now `KUBECONFIG` can switch normally

**Comment by Flying-Tom** [comment]
> > > `kurator-member1.config` and `kurator-member2.config`
> > 
> > 
> > Yes, `/root/.kube/kurator-member1.config`, `/root/.kube/kurator-member2.config` are valid paths and the file exist.
> > ```shell
> > root@whoami: file /root/.kube/kurator-member1.config
> > /root/.kube/kurator-member1.config: ASCII text, with very long lines (2261)
> > ```
> 
> You can open a new terminal window and try `export KUBECONFIG=/root/.kube/kurator-member.config`

I remove the export KUBECONFIG in my .zshrc and reboot, now KUBECONFIG can switch normally.

**Comment by LiZhenCheng9527** [comment]
well done 
/close
