### ISSUE TITLE
REQUEST: New member for yeyeye2333

### ISSUE THREAD

**Issue by yeyeye2333** [kurator-dev/kurator#677]
## GitHub Username
yeyeye2333

## Organization you are requesting membership in
Kurator

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing group] and [slack]
- [ ] I have watched kurator-dev/kurator on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more Kurator subprojects

## List of contributions to the Kurator project
- PRs reviewed / authored:
#667 
- Issues authored:
#653
- Issues responded to:

[community membership guidelines]: https://github.com/kurator-dev/kurator/community/membership/community-membership.md
[mailing group]: https://groups.google.com/g/kuator-dev
[slack]: https://join.slack.com/t/kurator-hq/shared_invite/zt-1sowqzfnl-Vu1AhxgAjSr1XnaFoogq0A
[watchers list]: https://github.com/kurator-dev/kurator/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication

**Comment by LiZhenCheng9527** [comment]
welcome！

**Comment by hzxuzhonghu** [comment]
Welcome

**Comment by hzxuzhonghu** [comment]
invitation has beend sent

**Comment by LiZhenCheng9527** [comment]
Done
