### ISSUE TITLE
REQUEST: New membership for Flying-Tom

### ISSUE THREAD

**Issue by Flying-Tom** [kurator-dev/kurator#682]
## GitHub Username

Flying-Tom
## Organization you are requesting membership in

kurator-dev

## Requirements

- [x] I have reviewed the [community membership guidelines]
- [x] I have joined in the community [mailing group] and [slack]
- [x] I have watched kurator-dev/kurator on GitHub to subscribe updates (My account appears in the [watchers list])
- [x] I have enabled [two-factor authentication] on my GitHub account
- [x] I am actively contributing to 1 or more Kurator subprojects
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

## List of contributions to the Kurator project
- PRs reviewed / authored:
#639
#658 
#659
#660 
#662 
#663 
#668 
#671 
#679 
#680 

- Issues authored:
#657 
#665 

- Issues responded to:

[community membership guidelines]: https://github.com/kurator-dev/kurator/community/membership/community-membership.md
[mailing group]: https://groups.google.com/g/kuator-dev
[slack]: https://join.slack.com/t/kurator-hq/shared_invite/zt-1sowqzfnl-Vu1AhxgAjSr1XnaFoogq0A
[watchers list]: https://github.com/kurator-dev/kurator/watchers
[two-factor authentication]: https://help.github.com/en/github/authenticating-to-github/about-two-factor-authentication

**Comment by hzxuzhonghu** [comment]
welcome , invitation sent

**Comment by LiZhenCheng9527** [comment]
Done
