### ISSUE TITLE
Provide production prometheus federation and long term storage capability

### ISSUE THREAD

**Issue by hzxuzhonghu** [kurator-dev/kurator#71]
**What would you like to be added**:

Previously we support prometheus federation, which is a basic model that can do multicluster metrics aggregate, but far from production ready.

I have investigated recently, and this one https://elastisys.com/long-term-metrics-storage-thanos-vs-cortex-vs-influxdb-vs-m3db-vs-victoriametrics-vs-timescaledb/ is the most complete comparison with clear criteria.

The conclusion is [thanos ](https://thanos.io/) is the winner for long time storage of multicluster metrics. 

As we can see thanos some some dependencies https://thanos.io/tip/thanos/getting-started.md/#dependencies Particularly we should pay attention to `object storage`, which we have not supported in kurator.

@daixiang0, for the s3 object storage, can we use [minio](https://github.com/minio/minio) to provide rather than using AWS directly?

**Comment by daixiang0** [comment]
For the short answer, yes. 

Minio is API compatible with Amazon S3 cloud storage service and it is built-in in Thanos.

If you want to use Huawei Store, it is also good, but it is not implemented as I know.

**Comment by hzxuzhonghu** [comment]
@daixiang0 @zirain who might be interested?

**Comment by zirain** [comment]
plan to add new plugin named `thanos` to `kurator`
- `Thanos Sidecar` will be deployed to every prometheus pod, which will upload TSDB blocks to object storage every 2h
- `Thanos Query` will be deployed to karmada host cluster, and exposed by ELB
- `Thanos Sidecar` will expose by ELB, and used in `Thanos Query` as store endpoint

cc @hzxuzhonghu @Xieql
